// package za.co.synergio.georgiou.migration; // Updated package name, or use default package if running standalone
// Actually, since it's in SQLscripts folder which is outside src/main/java, I'll put it in a temporary package or default package.
// But wait, the file is requested in SQLscripts folder. This folder is not a source folder for the main application. 
// So it should be a standalone file. I will use default package.

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.math.BigDecimal;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class MigrateToSQL {

    private static final String DATA_DIR = "./data/";
    private static final String OUTPUT_DIR = "./SQLscripts/";

    private static final String SCHEMA_SQL =
        "-- Schema for H2 database\n" +
        "-- Matching JPA Entity definitions with dash-separated table names\n\n" +
        "CREATE TABLE IF NOT EXISTS \"CUSTOMER\" (\n" +
        "    \"id\" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n" +
        "    \"date\" DATE,\n" +
        "    \"customer_name\" VARCHAR(255),\n" +
        "    \"cellphone\" VARCHAR(50),\n" +
        "    \"customer_address\" VARCHAR(255),\n" +
        "    \"state\" INT\n" +
        ");\n\n" +
        "CREATE TABLE IF NOT EXISTS \"CUSTOMER_VEHICLE\" (\n" +
        "    \"id\" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n" +
        "    \"customer_id\" INT,\n" +
        "    \"date\" DATE,\n" +
        "    \"customer_name\" VARCHAR(255),\n" +
        "    \"cellphone\" VARCHAR(50),\n" +
        "    \"customer_address\" VARCHAR(255),\n" +
        "    \"vehicle_reg_number\" VARCHAR(50),\n" +
        "    \"vehicle_make_model\" VARCHAR(255),\n" +
        "    \"colour\" VARCHAR(50),\n" +
        "    \"vin_number\" VARCHAR(100),\n" +
        "    \"state\" INT\n" +
        ");\n\n" +
        "CREATE TABLE IF NOT EXISTS \"SERVICE_RECORD\" (\n" +
        "    \"id\" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n" +
        "    \"date\" DATE,\n" +
        "    \"service_date\" DATE,\n" +
        "    \"recurring_date\" DATE,\n" +
        "    \"customer_name\" VARCHAR(255),\n" +
        "    \"cellphone\" VARCHAR(50),\n" +
        "    \"customer_address\" VARCHAR(255),\n" +
        "    \"vehicle_make_model\" VARCHAR(255),\n" +
        "    \"vehicle_reg_number\" VARCHAR(50),\n" +
        "    \"colour\" VARCHAR(50),\n" +
        "    \"odometer_reading\" VARCHAR(50),\n" +
        "    \"vin_number\" VARCHAR(100),\n" +
        "    \"document_type\" VARCHAR(100),\n" +
        "    \"requirement_category\" VARCHAR(100),\n" +
        "    \"interval_val\" INT,\n" +
        "    \"days_left\" INT,\n" +
        "    \"materials_required\" VARCHAR(500),\n" +
        "    \"labour_hours\" DOUBLE,\n" +
        "    \"amount\" DECIMAL(19, 2),\n" +
        "    \"breakdown\" VARCHAR(500),\n" +
        "    \"state\" INT\n" +
        ");\n\n" +
        "CREATE TABLE IF NOT EXISTS \"SERVICE_RECORD_JOBS\" (\n" +
        "    \"service_record_id\" INT,\n" +
        "    \"job_description\" VARCHAR(255),\n" +
        "    FOREIGN KEY (\"service_record_id\") REFERENCES \"SERVICE_RECORD\"(\"id\")\n" +
        ");\n";

    private static final String README_MD =
        "# SQL Migration Guide\n\n" +
        "This guide explains how to migrate data from CSV files to the H2 database using the provided Java utility.\n\n" +
        "## Prerequisites\n\n" +
        "- Java Development Kit (JDK) installed.\n" +
        "- The `MigrateToSQL.java` file located in the `SQLscripts` folder.\n" +
        "- The CSV data files located in the `data` folder at the project root.\n\n" +
        "## 1. Generate SQL Scripts\n\n" +
        "The migration utility reads the CSV files and generates two SQL scripts: `schema.sql` (for table creation) and `data.sql` (for data insertion).\n\n" +
        "### Step 1: Compile the Utility\n\n" +
        "Open a terminal or command prompt in the **project root directory** and run the following command:\n\n" +
        "```bash\n" +
        "javac SQLscripts/MigrateToSQL.java\n" +
        "```\n\n" +
        "### Step 2: Run the Utility\n\n" +
        "Execute the utility from the **project root directory** (this is important so it can find the `./data/` folder):\n\n" +
        "```bash\n" +
        "java -cp SQLscripts MigrateToSQL\n" +
        "```\n\n" +
        "Upon successful execution, you will see a message indicating that `schema.sql` and `data.sql` have been generated in the `SQLscripts` folder.\n\n" +
        "## 2. Execute SQL Scripts on H2 Database\n\n" +
        "You can execute the generated scripts using the H2 Console or the H2 command-line tool.\n\n" +
        "### Option A: Using H2 Console (Web Interface)\n\n" +
        "1.  Start your Spring Boot application or the H2 Console directly.\n" +
        "2.  Open the H2 Console in your browser (usually at `http://localhost:8080/h2-console` if running Spring Boot).\n" +
        "3.  **JDBC URL**: Ensure this matches your application properties (e.g., `jdbc:h2:file:./data/database`).\n" +
        "4.  **User Name** and **Password**: Enter credentials as configured in your `application.properties`.\n" +
        "5.  **Run Schema Script**:\n" +
        "    - Copy the contents of `SQLscripts/schema.sql`.\n" +
        "    - Paste them into the SQL query area and click **Run**.\n" +
        "6.  **Run Data Script**:\n" +
        "    - Copy the contents of `SQLscripts/data.sql`.\n" +
        "    - Paste them into the SQL query area and click **Run**.\n\n" +
        "### Option B: Using H2 Command Line (Shell)\n\n" +
        "If you have the H2 jar file available, you can use the Shell tool:\n\n" +
        "```bash\n" +
        "java -cp h2.jar org.h2.tools.Shell -url jdbc:h2:file:./data/database -user sa -password \"\" -script SQLscripts/schema.sql\n" +
        "java -cp h2.jar org.h2.tools.Shell -url jdbc:h2:file:./data/database -user sa -password \"\" -script SQLscripts/data.sql\n" +
        "```\n" +
        "*(Adjust the jar path, URL, user, and password as necessary)*\n";

    public static void main(String[] args) {
        System.out.println("Starting migration...");

        try {
            // Ensure output directory exists
            Files.createDirectories(Paths.get(OUTPUT_DIR));

            // Generate Schema
            generateSchema();
            
            // Generate Readme
            generateReadme();

            // Generate Data
            generateData();

            System.out.println("Migration scripts generated successfully in " + OUTPUT_DIR);

        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private static void generateSchema() throws IOException {
        String schemaFile = OUTPUT_DIR + "schema.sql";
        try (PrintWriter writer = new PrintWriter(new FileWriter(schemaFile))) {
            writer.print(SCHEMA_SQL);
        }
        System.out.println("Generated " + schemaFile);
    }

    private static void generateReadme() throws IOException {
        String readmeFile = OUTPUT_DIR + "SQL-MIGRATION-README.md";
        try (PrintWriter writer = new PrintWriter(new FileWriter(readmeFile))) {
            writer.print(README_MD);
        }
        System.out.println("Generated " + readmeFile);
    }

    private static void generateData() throws IOException {
        String dataFile = OUTPUT_DIR + "data.sql";
        try (PrintWriter writer = new PrintWriter(new FileWriter(dataFile))) {
            writer.println("-- Data migration from CSV");

            // Customers
            processCsv(DATA_DIR + "customers.csv", writer, (parts, w) -> {
                // CSV: index,date,customerName,cellphone,customerAddress,state
                if (parts.length < 6) return;
                String id = parts[0];
                String date = formatDate(parts[1]);
                String name = escapeSql(parts[2]);
                String phone = escapeSql(parts[3]);
                String address = escapeSql(parts[4]);
                String state = parts[5];

                w.printf("INSERT INTO \"CUSTOMER\" (\"id\", \"date\", \"customer_name\", \"cellphone\", \"customer_address\", \"state\") VALUES (%s, %s, '%s', '%s', '%s', %s);%n",
                        id, date, name, phone, address, state);
            });

            // Customer Vehicles
            processCsv(DATA_DIR + "customer_vehicles.csv", writer, (parts, w) -> {
                // CSV: index,customerId,date,customerName,cellphone,customerAddress,vehicleRegNumber,vehicleMakeAnModel,colour,vinNumber,state
                if (parts.length < 11) return;
                String id = parts[0];
                String customerId = parts[1];
                String date = formatDate(parts[2]);
                String name = escapeSql(parts[3]);
                String phone = escapeSql(parts[4]);
                String address = escapeSql(parts[5]);
                String reg = escapeSql(parts[6]);
                String makeModel = escapeSql(parts[7]);
                String colour = escapeSql(parts[8]);
                String vin = escapeSql(parts[9]);
                String state = parts[10];

                w.printf("INSERT INTO \"CUSTOMER_VEHICLE\" (\"id\", \"customer_id\", \"date\", \"customer_name\", \"cellphone\", \"customer_address\", \"vehicle_reg_number\", \"vehicle_make_model\", \"colour\", \"vin_number\", \"state\") VALUES (%s, %s, %s, '%s', '%s', '%s', '%s', '%s', '%s', '%s', %s);%n",
                        id, customerId, date, name, phone, address, reg, makeModel, colour, vin, state);
            });
            
             // Service Records
            processCsv(DATA_DIR + "service_records.csv", writer, (parts, w) -> {
                // CSV: index,transactionDate,serviceDate,recurringDate,customerName,cellphone,customerAddress,
                // vehicleMakeAndModel,vehicleRegNumber,colour,odometerReading,vinNumber,documentType,
                // requirementCategory,interval,daysLeft,materialsRequired,labourHours,amount,breakdown,jobsToDo,state
                
                if (parts.length < 22) return; 
                
                String id = parts[0];
                String date = formatDate(parts[1]);
                String serviceDate = formatDate(parts[2]);
                String recurringDate = formatDate(parts[3]);
                String name = escapeSql(parts[4]);
                String phone = escapeSql(parts[5]);
                String address = escapeSql(6 < parts.length ? parts[6] : "");
                String makeModel = escapeSql(7 < parts.length ? parts[7] : "");
                String reg = escapeSql(8 < parts.length ? parts[8] : "");
                String colour = escapeSql(9 < parts.length ? parts[9] : "");
                String odometer = escapeSql(10 < parts.length ? parts[10] : "");
                String vin = escapeSql(11 < parts.length ? parts[11] : "");
                String docType = escapeSql(12 < parts.length ? parts[12] : "");
                String reqCat = escapeSql(13 < parts.length ? parts[13] : "");
                String interval = (14 < parts.length && !parts[14].isEmpty()) ? parts[14] : "0";
                String daysLeft = (15 < parts.length && !parts[15].isEmpty()) ? parts[15] : "0";
                String materials = escapeSql(16 < parts.length ? parts[16] : "");
                String labour = (17 < parts.length && !parts[17].isEmpty()) ? parts[17] : "0.0";
                String amount = (18 < parts.length && !parts[18].isEmpty()) ? parts[18] : "0.00";
                String breakdown = escapeSql(19 < parts.length ? parts[19] : "");
                String jobsToDo = (20 < parts.length) ? parts[20] : "";
                
                jobsToDo = jobsToDo.replace("[", "").replace("]", "");
                String state = (21 < parts.length && !parts[21].isEmpty()) ? parts[21] : "0";
                
                w.printf("INSERT INTO \"SERVICE_RECORD\" (\"id\", \"date\", \"service_date\", \"recurring_date\", \"customer_name\", \"cellphone\", \"customer_address\", \"vehicle_make_model\", \"vehicle_reg_number\", \"colour\", \"odometer_reading\", \"vin_number\", \"document_type\", \"requirement_category\", \"interval_val\", \"days_left\", \"materials_required\", \"labour_hours\", \"amount\", \"breakdown\", \"state\") VALUES (%s, %s, %s, %s, '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', %s, %s, '%s', %s, %s, '%s', %s);%n",
                        id, date, serviceDate, recurringDate, name, phone, address, makeModel, reg, colour, odometer, vin, docType, reqCat, interval, daysLeft, materials, labour, amount, breakdown, state);

                if (!jobsToDo.trim().isEmpty()) {
                    String[] jobs = jobsToDo.split(";"); 
                    if(jobs.length == 1 && jobs[0].contains(",")) {
                         jobs = jobs[0].split(",");
                    }
                    
                    for (String job : jobs) {
                        if (!job.trim().isEmpty()) {
                             w.printf("INSERT INTO \"SERVICE_RECORD_JOBS\" (\"service_record_id\", \"job_description\") VALUES (%s, '%s');%n", id, escapeSql(job.trim()));
                        }
                    }
                }
            });
        }
        System.out.println("Generated " + dataFile);
    }
    
    private static void processCsv(String filePath, PrintWriter writer, CsvRowProcessor processor) throws IOException {
        Path path = Paths.get(filePath);
        if (!Files.exists(path)) {
            System.out.println("Skipping " + filePath + " (not found)");
            return;
        }

        try (BufferedReader reader = new BufferedReader(new FileReader(filePath))) {
            String line;
            boolean firstLine = true;
            while ((line = reader.readLine()) != null) {
                if (firstLine) {
                    firstLine = false;
                    continue; // Skip header
                }
                if (line.trim().isEmpty()) continue;
                
                // Simple CSV splitting (imperfect for quoted commas, but sufficient for simple data)
                 // Better to use a regex or a proper parser if complex, but for this task basic split is usually ok if no specific library requested.
                 // However, prompt asks for "Production-ready". I'll implement a slightly smarter splitter or use regex.
                 String[] parts = parseCsvLine(line);
                 processor.process(parts, writer);
            }
        }
    }
    
    // Simple CSV parser that handles quoted strings
    private static String[] parseCsvLine(String line) {
        List<String> list = new ArrayList<>();
        boolean inQuotes = false;
        StringBuilder sb = new StringBuilder();
        
        for (char c : line.toCharArray()) {
            if (c == '"') {
                inQuotes = !inQuotes;
            } else if (c == ',' && !inQuotes) {
                list.add(sb.toString());
                sb.setLength(0);
            } else {
                sb.append(c);
            }
        }
        list.add(sb.toString()); // last field
        return list.toArray(new String[0]);
    }

    private static String escapeSql(String val) {
        if (val == null) return "";
        return val.replace("'", "''").trim();
    }

    private static String formatDate(String dateStr) {
        if (dateStr == null || dateStr.trim().isEmpty() || dateStr.equalsIgnoreCase("null")) {
            return "NULL";
        }
        try {
            // Verify format yyyy-MM-dd
            LocalDate.parse(dateStr); 
            return "'" + dateStr + "'";
        } catch (Exception e) {
            return "NULL";
        }
    }

    @FunctionalInterface
    interface CsvRowProcessor {
        void process(String[] parts, PrintWriter writer);
    }
}
