-- Schema for H2 database
-- Matching JPA Entity definitions with dash-separated table names

CREATE TABLE IF NOT EXISTS "CUSTOMER" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "date" DATE,
    "customer_name" VARCHAR(255),
    "cellphone" VARCHAR(50),
    "customer_address" VARCHAR(255),
    "state" INT
);

CREATE TABLE IF NOT EXISTS "CUSTOMER_VEHICLE" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "customer_id" INT,
    "date" DATE,
    "customer_name" VARCHAR(255),
    "cellphone" VARCHAR(50),
    "customer_address" VARCHAR(255),
    "vehicle_reg_number" VARCHAR(50),
    "vehicle_make_model" VARCHAR(255),
    "colour" VARCHAR(50),
    "vin_number" VARCHAR(100),
    "state" INT
);

CREATE TABLE IF NOT EXISTS "SERVICE_RECORD" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "date" DATE,
    "service_date" DATE,
    "recurring_date" DATE,
    "customer_name" VARCHAR(255),
    "cellphone" VARCHAR(50),
    "customer_address" VARCHAR(255),
    "vehicle_make_model" VARCHAR(255),
    "vehicle_reg_number" VARCHAR(50),
    "colour" VARCHAR(50),
    "odometer_reading" VARCHAR(50),
    "vin_number" VARCHAR(100),
    "document_type" VARCHAR(100),
    "requirement_category" VARCHAR(100),
    "interval_val" INT,
    "days_left" INT,
    "materials_required" VARCHAR(500),
    "labour_hours" DOUBLE,
    "amount" DECIMAL(19, 2),
    "breakdown" VARCHAR(500),
    "state" INT
);

CREATE TABLE IF NOT EXISTS "SERVICE_RECORD_JOBS" (
    "service_record_id" INT,
    "job_description" VARCHAR(255),
    FOREIGN KEY ("service_record_id") REFERENCES "SERVICE_RECORD"("id")
);
