-- precise schema for H2 database
CREATE TABLE IF NOT EXISTS customer (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE,
    customer_name VARCHAR(255),
    cellphone VARCHAR(50),
    customer_address VARCHAR(255),
    state INT
);

CREATE TABLE IF NOT EXISTS customer_vehicle (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INT,
    date DATE,
    customer_name VARCHAR(255),
    cellphone VARCHAR(50),
    customer_address VARCHAR(255),
    vehicle_reg_number VARCHAR(50),
    vehicle_make_model VARCHAR(255),
    colour VARCHAR(50),
    vin_number VARCHAR(100),
    state INT
);

CREATE TABLE IF NOT EXISTS service_record (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE,
    service_date DATE,
    recurring_date DATE,
    customer_name VARCHAR(255),
    cellphone VARCHAR(50),
    customer_address VARCHAR(255),
    vehicle_make_model VARCHAR(255),
    vehicle_reg_number VARCHAR(50),
    colour VARCHAR(50),
    odometer_reading VARCHAR(50),
    vin_number VARCHAR(100),
    document_type VARCHAR(100),
    requirement_category VARCHAR(100),
    interval_val INT,
    days_left INT,
    materials_required VARCHAR(500),
    labour_hours DOUBLE,
    amount DECIMAL(19, 2),
    breakdown VARCHAR(500),
    state INT
);

CREATE TABLE IF NOT EXISTS service_record_jobs (
    service_record_id INT,
    job_description VARCHAR(255),
    FOREIGN KEY (service_record_id) REFERENCES service_record(id)
);
